export const HOME = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const PASSWORD_FORGET = '/pw-forget'
export const CHECKOUT = '/checkout'
export const DISCOVER = '/product/discover-homeowner'
