export const cartInitState = {
  items: [
    {
      id: 0,
      title:'Discover Homeowner',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 0,
      type: 'single',
    },
    {
      id: 1,
      title:'Discover Homeowner+',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 500,
      type: 'single',
    },
    {
      id: 2,
      title:'Discover Business',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 1000,
      type: 'monthly',
    },
    {
      id: 3,
      title:'Compare Homeowner',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 500,
      type: 'single',
    },
    {
      id: 4,
      title:'Compare Homeowner+',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 1000,
      type: 'single',
    },
    {
      id: 5,
      title:'Compare Business',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 6000,
      type: 'monthly',
    },
    {
      id: 6,
      title:'Examine Homeowner',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 2500,
      type: 'single',
    },
    {
      id: 7,
      title:'Examine Business',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 2500,
      type: 'monthly',
    },
    {
      id: 8,
      title:'Certify Homeowner',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 1000,
      type: 'single',
    },
    {
      id: 9,
      title:'Certify Business',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 1000,
      type: 'monthly',
    },
    {
      id: 10,
      title:'Reduce',
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
      price: 39500,
      type: 'single',
    },
  ],
  addedItems:[],
  total: 0,
}
